### ISSUE TITLE
TypeError: Cannot read property 'maxSockets' of undefined

### ISSUE THREAD

**Issue by rederlo** [stevenvachon/limited-request-queue#16]
var availableSockets = instance.options.maxSockets - instance.activeSockets;
                                                ^

TypeError: Cannot read property 'maxSockets' of undefined
    at startNext (/home/rodrigo/projects/node/spyder/node_modules/limited-request-queue/lib/index.js:220:42)
    at Timeout.RequestQueue.resume [as _onTimeout] (/home/rodrigo/projects/node/spyder/node_modules/limited-request-queue/lib/index.js:96:2)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by stevenvachon** [comment]
Do you experience this with v4.0.0 ?
